alias fortunecow='fortune | cowsay'
alias RAINBOW='yes xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx | lolcat'
alias inxii='inxi -Fx' 
alias tuxsay='cowsay -f tux'
alias clock='while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &'
alias aliases='nano ~/.bash_aliases && . ~/.bash_aliases'
alias strpwd='read -s pass; echo $pass | md5sum | base64 | cut -c -16'
alias wgetsite='wget --random-wait -r -p -e robots=off -U mozilla'
alias nano='nano -i -l -m -$'
alias manfred='cmatrix -b -a -u 6 -C green'
alias morten='cmatrix -b -a -u 6 -C red'
alias la='ls -la'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
