set number
set linebreak
set showmatch
set visualbell
set hlsearch
set incsearch
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
set ruler
set undolevels=1000

filetype indent plugin on
syntax on