" Use XDG directories
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif


" Indention
"" Indent automatically
set autoindent
"" Convert tabs to spaces
set expandtab
"" When tabbing, round to multiple of shiftwidth
set shiftround
set shiftwidth=4
"" Use tabstop spaces when tabbing
set smarttab
set tabstop=4
"" Use file-dependent auto indention
filetype indent on

" Search
"" Highlight results
set hlsearch
"" Case-insensitive search by default
set ignorecase
"" Also search for partial matches
set incsearch
"" Switch to case-sensitive if search has any uppercase letters
set smartcase

" UI
"" Show cursor position
set ruler
"" Tab complete is a menu
set wildmenu
"" Line numbers relative to current position (helps with commands)
set number
set relativenumber
"" Don't beep on error
set noerrorbells
set visualbell
"" Enable mouse
set mouse=a
"" Set xterm title
set title
"" Use colors visible on a dark background
set background=dark
" Enable syntax highlighting
syntax enable

" Use line wrapping
set wrap

" Don't break the line in the middle of a word
set linebreak

" Smart Home key
noremap <expr> <silent> <Home> col('.') == match(getline('.'),'\S')+1 ? '0' : '^'
imap <silent> <Home> <C-O><Home>

" Key mappings
vnoremap <C-c> "+y
map <C-p> "+P

" Filetype specific
autocmd FileType make setlocal noexpandtab
